### ISSUE TITLE
Size Enum Question/Recommendation

### ISSUE THREAD

**Issue by JoshRosenstein** [reflex-ui/reflex-ui#4]
Hello, found your repo as I've been searching through github for good typing examples and methodologies. I've taken an interest in your coding style as its more legible and declarative then other repos Ive studied. 

Since I am still relatively new to this space, I wanted to ask if this simple change would be better or not:

Changing https://github.com/reflex-ui/reflex-ui/blob/a0c7542db39559ed70c4a3e31a3fa252c31a1741/packages/core/src/sizing/isSizeEnumValue.ts#L8-L15
to
```ts
import { Size } from './Size';
export const isSizeEnumValue = (value: string): value is Size => value in Size
```
Then

https://github.com/reflex-ui/reflex-ui/blob/a0c7542db39559ed70c4a3e31a3fa252c31a1741/packages/core/src/sizing/getSizedDataValue.ts#L8-L18
to
```ts
import { isSizeEnumValue } from '../sizing/isSizeEnumValue';
import { SizedData } from './SizedData';

export const getSizedDataValue = <Data extends SizedData<Value>, Value>(
  sizedObject: Data,
  size: Value,
) =>
  typeof size === 'string' && isSizeEnumValue(size)
    ? sizedObject[size]
    : size;
```

**Comment by flsilva** [comment]
Hi Josh! Thank you, I'm glad you see it that way, I've been putting a lot of time and effort to make the codebase as clean and declarative as possible.

I like your solution a lot, it's very smart and clean, but it would require an extra change to make it work. As is, we always get `false` in the following line:

`value in Size`

That's because the `Size` `enum` is defined this way:

```ts
export enum Size {
  XXS = 'xxsmall',
  XS = 'xsmall',
  S = 'small',
  M = 'medium',
  L = 'large',
  XL = 'xlarge',
  XXL = 'xxlarge',
}
```

And this is the transpiled JS version:

```js
export var Size;
(function (Size) {
    Size["XXS"] = "xxsmall";
    Size["XS"] = "xsmall";
    Size["S"] = "small";
    Size["M"] = "medium";
    Size["L"] = "large";
    Size["XL"] = "xlarge";
    Size["XXL"] = "xxlarge";
})(Size || (Size = {}));
```

So as you can see, `value` in `value in Size` evaluates to `xxsmall`, `xsmall`, etc, but the enum (JS var) is indexed by the name of its constants (`XXS`, `XS`, etc) not by their values (`xxsmall`, `xsmall`, etc) , TS does that automatically for us. That's why we'd always get `false` from `value in Size`.

To make it work we'd have to change the `Size` enum to have their constant names and values the same, which could be either this:

```ts
export enum Size {
  XXS = 'XXS',
  XS = 'XS',
  S = 'S',
  M = 'M',
  L = 'L',
  XL = 'XL',
  XXL = 'XXL',
}
```

Or this:

```ts
export enum Size {
  xxsmall = 'xxsmall',
  xsmall = 'xsmall',
  small = 'small',
  medium = 'medium',
  large = 'large',
  xlarge = 'xlarge',
  xxlarge = 'xxlarge',
}
```

Currently we use `Size` as e.g. `<Surface margin={Size.S} size={Size.XL}>`, and in the React DevTools we can see it like this:

```
<RfxSurface margin="small" size="xlarge">
```

I like the short version for coding, it's more succinct yet meaningful since it's always prefixed with `Size.`. And having the long form on DevTools might make it easier to debug (since we don't have `Size.` prefix), but I guess having the short version there would be fine too, like:

```
<RfxSurface margin="S" size="XL">
```

Also, if we make either change to `Size`, we'd have to change several places in the `core-md` package to change sized objects from:

```
{
  xxsmall: {},
  xsmall: {},
  ...
}
```

To:

```
{
  XXS: {},
  XS: {},
  ...
}
```

Not a big deal, but something to keep in mind.

What do you think? Does the short form in DevTools look fine for you?

I'll keep this issue open for now, and will think about changing `Size` values to the short form, having the short version on DevTools might be cool to reduce clutter. I'll let you know if I decide to make this change, in that case if you have time and are interested to contribute to the project, you could open a PR.

Also, feel free to open new issues to discuss anything. I'm planning to release the first public version in a few months, and I can see a lot of potential for the framework.

**Comment by JoshRosenstein** [comment]
@flsilva  Thank you for a taking the time out and explaining that. I completely missed the difference in the name & values!

This originally came to mind after studying some patterns in [Microsoft/fast-dna](https://github.com/Microsoft/fast-dna)

For Example:
[this Enum](https://github.com/Microsoft/fast-dna/blob/a5e4a7fc1e69c820b352c7469dc6472ae0a4de34/packages/fast-layouts-react/src/grid/grid.props.ts#L21-L25) used [here](https://github.com/Microsoft/fast-dna/blob/a5e4a7fc1e69c820b352c7469dc6472ae0a4de34/packages/fast-layouts-react/src/grid/grid.tsx#L131-L132
)

 After seeing the name differences now, I do like your original thought process of having  short version for coding and long form on DevTools. 

However, Im trying to think of a way to keep the short-toLong method, but limit the amount of changes required if the Enum ever has to change. For example if later on you need to alter a value or add one, you would have to also update `isSizeEnumValue` and `allSizes`.

So maybe something like this:
```ts
export const allSize:Size[]=Object.values(Size)

export const isSizeEnumValue = (value: string ): value is Size => Object.values(Size).includes(value)
// Or
export const isSizeEnumValue = (value: string ): value is Size => allSize.includes(value as Size)
```

**Comment by flsilva** [comment]
Hey @JoshRosenstein!

That looks pretty nice! I just tested it and it works.

I'm also always looking for smart ways to write code, and that makes a lot of sense. Would you like to send a PR? I'll be glad to review and merge it. Otherwise I can push the change myself.

Thanks.
